### ISSUE TITLE
Add an option of sync different computers .

### ISSUE THREAD

**Issue by wilon** [facelessuser/FavoriteFiles#16]
`favorite_files_list_computer_name.json`

It would be useful if Sublime Text settings are synced across different computers.

**Comment by facelessuser** [comment]
There are already solutions to do this.  Sync your sublime settings in a repo, dropbox, or there might be a plugin that already does this.  Personally I don't think it makes sense to sync favoritefiles  to multiple computers as files and file location can differ from machine to machine.

**Comment by facelessuser** [comment]
As there are already sync solutions available, there is no real actionable item.  I'm closing this issue.
