### ISSUE TITLE
[Question] "Quick" add to favorites - keyboard shortcut

### ISSUE THREAD

**Issue by backslash-f** [facelessuser/FavoriteFiles#22]
Hallo,

Any way to add a file to favorites providing default answers for the default questions?

For example:

```
{
    "keys": [
      "super+shift+a"
    ],
    "command": "favorite_files_add",
    "args": {
      "Add current file": "true",
      "No group": "true"
    }
  }
```

Thanks!

**Comment by facelessuser** [comment]
There currently isn't an easy way to do that.

**Comment by backslash-f** [comment]
Mmkay. I guess we can close this issue then. Thanks anyway! 👍
