### ISSUE TITLE
Possible feature: Folder mode?

### ISSUE THREAD

**Issue by mgussekloo** [facelessuser/FavoriteFiles#27]
Hi,

I've added a "Folder mode" for my own use case. It organizes favorites by folder instead of globally / per project.
This lets me open a project folder with "Sesame" plugin in Sublime, and work with favorites that are specific for that folder without creating a Project.

Is this something that would be worthwile to add to the plugin? I could make a [pull request](https://github.com/facelessuser/FavoriteFiles/compare/master...mgussekloo:FavoriteFiles:master). Let me know what you think.

**Comment by mgussekloo** [comment]
Thanks for the reply. It puts a favorite_files_list.json in the current window's root folder and uses that, whenever you run a Favorite Files command. The main advantage is that it lets you use Favorite Files without having to use global favorites (less useful if you open a lot of separate projects with similarly named files), or Project-mode (only works when you already use projects in your workflow). I linked to the commit, if you want to have a look at it. For me it's a nice addition, but that may be my personal preference.

Thanks for the plugin!

**Comment by facelessuser** [comment]
So you are stating that multiple jsons would under a folder hierarchy or that only one would be created at the root level of the folder hierarchy, like a project mode without a project file?

**Comment by mgussekloo** [comment]
Yes, "project mode without a project file" is a good description, tbh! I might be doing it wrong by not using projects. I have a lot of Wordpress installs where I use the "Sesame Open" plugin to get the folder into Sublime and then go to interesting files in the wp-content/themes/custom-code/etc. subdirectory through Favorite Files.

**Comment by facelessuser** [comment]
TBH, my suggestion would be if you want project like functionality...use projects :). You have to understand that maintaining two ways to essentially due projects is probably more than I'd care to do. Why re-invent the wheel for solution that already exist?

**Comment by mgussekloo** [comment]
I think the feature adds value for those who don't use projects like myself, but I understand your reasoning. I think we can close the issue, thanks again for the plugin.
