### ISSUE TITLE
Open favorite files no longer works

### ISSUE THREAD

**Issue by aldendaniels** [facelessuser/FavoriteFiles#8]
After taking the update to **3077**, the favorite files plugin no longer works. After working around #7 and adding a favorite, I get the following message when I try to open the saved favorite:

![screen shot 2015-03-20 at 9 16 03 am](https://cloud.githubusercontent.com/assets/4658558/6753112/be50e0c4-cee1-11e4-90a5-9f9faba8895d.png)

**Comment by facelessuser** [comment]
>  After working around #7

Meaning you are now running off the tip of the main and not using the last official release?  I need to make sure we are on the same page.

### Assuming the above answer is "Yes, I am now on the latest commit of the main branch":

- Did you restart after upgrading to the latest FavoriteFiles?
- Do you get an error when trying to add a favorite? (which would explain why no favorites are found).
- What do you see in your `Packages\User\favorite_files_list.json` file?

**Comment by facelessuser** [comment]
Maybe also upgrade again as 3077 sounds like it had some problems:

```
Build 3078
Release Date: 19 March 2015
Fixed a plugin_host regression in 3077
```

**Comment by aldendaniels** [comment]
@facelessuser - thanks for checking in. This issue was also occurring for me on builds **3078** and **3079**. 

I've switched to [sublime-quick-file-open](https://github.com/gsingh93/sublime-quick-file-open) since it accommodates my very simple use case so I'm not using *Favorite Files* at the moment.

Since no-one else has chimed in then perhaps this issue is unique to me, in which case feel free to close.

Cheers

**Comment by facelessuser** [comment]
Since none of the questions I asked were answered, I have no additional info to go on anyways to try and help.  I will just assume this was unique to your setup.
