### ISSUE TITLE
add the list of favorite files to a "virtual" folder

### ISSUE THREAD

**Issue by diniremix** [facelessuser/FavoriteFiles#9]
Hi, excellent your plugin, I ask a question, you can add the list of favorite files to a "virtual" folder within the project, something like this:

![example](http://i.imgur.com/tIZhXGW.jpg)

thank you very much, sorry for the translation, use **Google Translate**

**Comment by facelessuser** [comment]
Sublime Text can only have "real" folders in the sidebar.  I guess they could do symlinks too, but basically they have to exist on disk.

Not sure what your use case is, but if you are looking for "project specific" favorite files, you can use the following option: https://github.com/facelessuser/FavoriteFiles#favorite-files-toggle-per-project.

**Comment by diniremix** [comment]
Well, I have the "enable_per_projects" option as follows:
```json
{
    "enable_per_projects": true
}
```

If correct, the files must exist, but the project file Sublime Text 2 enables the following settings:

```json
{
	"folders":
	[
		{
			"name": "Favorite Files",
			"file_exclude_patterns": ["*.min.js"],
			"path": "src/js/filters/"
		},		
		{
			"folder_exclude_patterns":
			[
				"node_modules"
			],
			"name": "Materialize",
			"path": "/home/diniremix/www/Materialize",
			"path": "src/"
		}
	]	
}
```
and place any name, each project folder, the idea is that you can create a folder for the favorite files and add to sidebar for faster location, such as browser bookmarks, for example.
finally would be as follows.

![project](http://i.imgur.com/jCRMwey.jpg)

regards.

Sorry for the translation, I do not speak English.

**Comment by facelessuser** [comment]
Hmm.  This is interesting.   While I won't promise this, I may investigate the pros and cons of something like this.  I will leave this open as a possibility.

**Comment by ziedzic** [comment]
+1

**Comment by facelessuser** [comment]
While I can understand the desire for this feature, this just isn't a feature I would use.

Thanks for your interest, but maybe there is another plugin or there that will give you something closer to what you want. Or maybe in time you will have the current interface grow on you.  Either way I'll be closing this issue as this issue had been open for 2 years and I have found the motivation to implement this specific feature.
